# -*- coding: utf-8 -*-
"""analysis-tingkat-pengangguran-berprov.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROUnVbpU0K_7D8nXm9wQM7NN6gFHitPn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pengangguran_df = pd.read_csv('tingkat-pengagguran-prov.csv')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pengangguran_df

pengangguran_df = pd.read_csv('tingkat-pengagguran-prov.csv')

# Melihat nama kolom
print(pengangguran_df.columns)

pengangguran_df.columns = ['Provinsi','Februari', 'Agustus']
print(pengangguran_df.head())

pengangguran_df.head(50)

pengangguran_df.info()

pengangguran_df.isna().sum()

print("Jumlah duplikasi: ", pengangguran_df.duplicated().sum())

pengangguran_df.describe()

pengangguran_df.drop_duplicates(inplace=True)

print("Jumlah duplikasi: ", pengangguran_df.duplicated().sum())

pengangguran_df[pengangguran_df.Provinsi.isna()]

pengangguran_df.Provinsi.value_counts()

pengangguran_df = pengangguran_df.dropna(subset=['Provinsi', 'Februari', 'Agustus'])

pengangguran_df.head(50)

pengangguran_df = pengangguran_df.reset_index(drop=True) # Correct the variable name from 'penggangguran_df' to 'pengangguran_df'

pengangguran_df.head(50)

pengangguran_df.replace('-', '0', inplace=True)
pengangguran_df[['Februari', 'Agustus']] = pengangguran_df[['Februari', 'Agustus']].astype(float)

# Menampilkan DataFrame untuk memastikan
print(pengangguran_df.head(50))

pengangguran_df.info()

pengangguran_df.head(50)

import pandas as pd # Import the pandas library

Provinsi_columns = ["Provinsi"]

for column in Provinsi_columns:
  pengangguran_df[column] = pengangguran_df[column].astype(str) # Use astype(str) for string conversion

pengangguran_df.describe()

pengangguran_df.info()

print("Jumlah duplikasi: ", pengangguran_df.duplicated().sum())

pengangguran_df.isna().sum()

pengangguran_df.describe()

pengangguran_df.describe(include="all")

pengangguran_df.head(50)

# Menghitung total tingkat pengangguran per provinsi
pengangguran_df["total_tingkat"] = pengangguran_df["Februari"] + pengangguran_df["Agustus"]

# Menampilkan DataFrame yang telah diperbarui
print(pengangguran_df)

pengangguran_df.describe(include="all")

import matplotlib.pyplot as plt
import seaborn as sns

# Menghitung rata-rata tingkat pengangguran per provinsi
mean_unemployment = pengangguran_df.groupby('Provinsi')[['Februari', 'Agustus']].mean().reset_index()

# Menambahkan kolom Total
mean_unemployment['Total'] = mean_unemployment['Februari'] + mean_unemployment['Agustus']

# Visualisasi rata-rata tingkat pengangguran Februari per provinsi
plt.figure(figsize=(14, 7))
sns.barplot(x='Provinsi', y='Februari', data=mean_unemployment, palette='viridis')
plt.title('Rata-rata Tingkat Pengangguran Februari per Provinsi')
plt.xticks(rotation=90)
plt.xlabel('Provinsi')
plt.ylabel('Rata-rata Tingkat Pengangguran (%)')
plt.show()

# Visualisasi rata-rata tingkat pengangguran Agustus per provinsi
plt.figure(figsize=(14, 7))
sns.barplot(x='Provinsi', y='Agustus', data=mean_unemployment, palette='viridis')
plt.title('Rata-rata Tingkat Pengangguran Agustus per Provinsi')
plt.xticks(rotation=90)
plt.xlabel('Provinsi')
plt.ylabel('Rata-rata Tingkat Pengangguran (%)')
plt.show()

# Visualisasi total tingkat pengangguran per provinsi
plt.figure(figsize=(14, 7))
sns.barplot(x='Provinsi', y='Total', data=mean_unemployment, palette='viridis')
plt.title('Total Tingkat Pengangguran per Provinsi')
plt.xticks(rotation=90)
plt.xlabel('Provinsi')
plt.ylabel('Total Tingkat Pengangguran (%)')
plt.show()

# Select only the numeric columns for correlation calculation
numeric_df = pengangguran_df[['Februari', 'Agustus']]

# Calculate the correlation matrix
correlation = numeric_df.corr()

# Print the correlation matrix
print(correlation)

# Visualize the correlation heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(correlation, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Heatmap Korelasi Antar Kolom')
plt.show()

plt.figure(figsize=(16, 6))
sns.barplot(x='Provinsi', y='total_tingkat', data=pengangguran_df, palette='viridis')
plt.title('Total Tingkat Pengangguran Per Provinsi')
plt.xticks(rotation=90)
plt.xlabel('Provinsi')
plt.ylabel('Total Tingkat Pengangguran')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 8))  # Ukuran yang lebih besar untuk tampilan yang lebih baik
sns.scatterplot(x='Februari', y='Agustus', hue='Provinsi', data=pengangguran_df, palette='tab10', s=100, edgecolor='w')

plt.title('Tingkat Pengangguran Februari vs Agustus Per Provinsi', fontsize=16)
plt.xlabel('Tingkat Pengangguran Februari', fontsize=14)
plt.ylabel('Tingkat Pengangguran Agustus', fontsize=14)
plt.legend(title='Provinsi', bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()  # Mengatur layout agar tidak ada elemen yang terpotong
plt.show()

plt.figure(figsize=(18, 8))
bar_plot = sns.barplot(x='Provinsi', y='total_tingkat', data=pengangguran_df, palette='viridis')
plt.title('Total Tingkat Pengangguran Per Provinsi')
plt.xticks(rotation=90)
plt.xlabel('Provinsi')
plt.ylabel('Total Tingkat Pengangguran')

# Menambahkan label pada bar
for p in bar_plot.patches:
    bar_plot.annotate(format(p.get_height(), '.2f'),
                      (p.get_x() + p.get_width() / 2., p.get_height()),
                      ha='center', va='center',
                      xytext=(0, 9),
                      textcoords='offset points')

plt.show()

# Assuming 'pengangguran_df' is your DataFrame containing all the data
pengangguran_df.to_csv("all_data_tingkatpeng.csv", index=False)

from google.colab import files

# Mengunggah file CSV yang telah dibuat
files.download("all_data_tingkatpeng.csv")